from __future__ import annotations

from typing import Protocol

from sonya_runtime.actions.models import RuntimeTaskPayload
from sonya_runtime.tasks.models import TaskRecord


class TaskStore(Protocol):
    def create_task(self, payload: RuntimeTaskPayload) -> TaskRecord: ...

    def get_task(self, task_id: str) -> TaskRecord | None: ...

    def list_tasks(self, status: str | None = None, limit: int = 50) -> list[TaskRecord]: ...

    def claim_next_task(self, worker_id: str, allowed_kinds: set[str] | None = None) -> TaskRecord | None: ...

    def mark_running(self, task_id: str, worker_id: str) -> TaskRecord | None: ...

    def mark_done(self, task_id: str, result_summary: str, result_payload: dict | None = None) -> TaskRecord | None: ...

    def mark_failed(self, task_id: str, error_text: str) -> TaskRecord | None: ...

    def cancel_task(self, task_id: str) -> TaskRecord | None: ...

    def get_open_tasks_for_principal(self, principal_id: str, origin_chat_id: str | None = None) -> list[TaskRecord]: ...
